"use client";
import { useEffect, useState } from "react";
import { fragments } from "@/games/fragments";
import { puzzles } from "@/games/puzzles";
import { emptyGameState, loadGameState, saveGameState, type GameState } from "@/lib/gameState";
import { TerminalPuzzle } from "@/components/TerminalPuzzle";
import { AudioPuzzle } from "@/components/AudioPuzzle";
import { MapPuzzle } from "@/components/MapPuzzle";
import { ElectricalPuzzle } from "@/components/ElectricalPuzzle";
import { TimelinePuzzle } from "@/components/TimelinePuzzle";

type View = "home" | "progress" | "fragments" | "puzzle" | "success" | "meta";
const normalizeAnswer = (answer: string) => answer.normalize("NFD").replace(/[\u0300-\u036f]/g, "").trim().replace(/\s+/g, " ").toLocaleUpperCase("fr-FR");
const check = (answer: string, expected: string) => normalizeAnswer(answer) === normalizeAnswer(expected);
const polybiusRows = [["A","B","C","D","E"],["F","G","H","I","K"],["L","M","N","O","P"],["Q","R","S","T","U"],["V","W","X","Y","Z"]];

export default function Home() {
  const [state, setState] = useState<GameState>(emptyGameState), [view, setView] = useState<View>("home"), [ready, setReady] = useState(false), [answer, setAnswer] = useState(""), [error, setError] = useState(false), [hintVisible, setHintVisible] = useState(false), [activePuzzleId, setActivePuzzleId] = useState(puzzles[0].id), [justSolvedId, setJustSolvedId] = useState(puzzles[0].id), [open, setOpen] = useState<number | null>(null);
  useEffect(() => { const timer = window.setTimeout(() => { const persisted = loadGameState(); setState(persisted); setView(persisted.started ? "progress" : "home"); setReady(true); }, 0); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (ready) saveGameState(state); }, [ready, state]);
  const solved = state.solvedPuzzleIds.length, complete = solved === puzzles.length, nextPuzzle = puzzles.find((puzzle) => !state.solvedPuzzleIds.includes(puzzle.id)), current = puzzles.find((puzzle) => puzzle.id === activePuzzleId) ?? puzzles[0], justSolved = puzzles.find((puzzle) => puzzle.id === justSolvedId) ?? puzzles[0];
  const begin = () => { setState((s) => ({ ...s, started: true })); setView("progress"); };
  const markSolved = (puzzleId: string) => { const puzzle = puzzles.find((item) => item.id === puzzleId) ?? puzzles[0]; setState((s) => ({ ...s, solvedPuzzleIds: s.solvedPuzzleIds.includes(puzzle.id) ? s.solvedPuzzleIds : [...s.solvedPuzzleIds, puzzle.id], unlockedFragmentIds: s.unlockedFragmentIds.includes(puzzle.fragmentId) ? s.unlockedFragmentIds : [...s.unlockedFragmentIds, puzzle.fragmentId] })); setJustSolvedId(puzzle.id); setView("success"); };
  const validate = () => { if (!check(answer, current.demoAnswer ?? "")) { setError(true); return; } markSolved(current.id); };
  const openPuzzle = (puzzleId: string) => { setActivePuzzleId(puzzleId); setAnswer(""); setError(false); setHintVisible(false); setView("puzzle"); };
  const reset = () => { localStorage.removeItem("dossier-4x100-game-state"); setState(emptyGameState); setView("home"); setAnswer(""); };
  return <main className="app-shell"><i className="orb one"/><i className="orb two"/><section className="app-frame">
    {view !== "home" && <header><button onClick={() => setView("progress")}>DOSSIER 4x100</button><span className="header-code">ARCHIVE / 04.100</span><i className="live"/></header>}
    {view === "home" && <div className="home fade"><div className="monogram">D</div><p className="eyebrow">SYSTÈME D’ARCHIVAGE · UNITÉ 04</p><h1>DOSSIER<br/>4x100</h1><p className="subtitle">Système de récupération mémorielle</p><p className="intro">Votre mémoire a été fragmentée.<br/>Six fragments doivent être récupérés.<br/>Résolvez les énigmes pour les retrouver.</p><Dots count={0}/><Action onClick={begin}>Initialiser la session</Action><small>Accès personnel · Protocole 04.100</small></div>}
    {view === "progress" && <div className="content fade"><p className="eyebrow">ÉTAT DE LA RÉCUPÉRATION</p><Title title="Fragments récupérés" count={solved}/><Dots count={solved}/><Grid unlocked={state.unlockedFragmentIds}/><section className="next"><p className="eyebrow">{complete ? "SYSTÈME COMPLET" : "PROCHAINE ÉTAPE"}</p>{complete ? <><h3>Tous les fragments ont été récupérés.</h3><p>Vous avez maintenant tout ce qu’il vous faut.</p><Action onClick={() => setView("meta")}>Assembler les fragments</Action></> : nextPuzzle ? <><h3><em>0{nextPuzzle.order}</em> {nextPuzzle.title}</h3><p>{nextPuzzle.shortDescription}</p><Action onClick={() => openPuzzle(nextPuzzle.id)}>Commencer l’énigme</Action></> : null}</section></div>}
    {view === "puzzle" && current.id === "polybius-square" && <div className="content puzzle polybius fade"><button className="back" onClick={() => setView("progress")}>← Retour</button><p className="eyebrow">ÉNIGME 01</p><h2>{current.title}</h2><p className="intro">{current.introduction}</p><div className="cipher-message" aria-label="Message chiffré">33 · 34 · 32 <i>/</i> 14 · 15 <i>/</i> 55 · 15 · 45 · 43</div><div className="polybius-grid" aria-label="Carré de Polybe"><span className="corner"/>{[1,2,3,4,5].map((number) => <span className="axis" key={`column-${number}`}>{number}</span>)}{polybiusRows.map((row, rowIndex) => <div className="polybius-row" key={`row-${rowIndex}`}><span className="axis">{rowIndex + 1}</span>{row.map((letter) => <span key={letter}>{letter}</span>)}</div>)}</div>{hintVisible ? <p className="hint"><b>Indice</b>Chaque nombre indique une ligne, puis une colonne.</p> : <button className="hint-button" onClick={() => setHintVisible(true)}>Afficher l’indice <span>+</span></button>}<label htmlFor="answer">Message déchiffré</label><input id="answer" autoCapitalize="characters" autoComplete="off" value={answer} onChange={(e) => {setAnswer(e.target.value);setError(false);}} onKeyDown={(e) => e.key === "Enter" && validate()} placeholder="Saisir le message"/><p className="error">{error && "Réponse non reconnue. Vérifiez la grille et réessayez."}</p><Action onClick={validate}>Valider</Action></div>}
    {view === "puzzle" && current.id === "terminal-access" && <TerminalPuzzle onBack={() => setView("progress")} onSolved={() => markSolved(current.id)}/>}
    {view === "puzzle" && current.id === "minutes-crimes" && <AudioPuzzle onBack={() => setView("progress")} onSolved={() => markSolved(current.id)}/>}
    {view === "puzzle" && current.id === "off-screen-map" && <MapPuzzle onBack={() => setView("progress")} onSolved={() => markSolved(current.id)}/>}
    {view === "puzzle" && current.id === "electrical-failure" && <ElectricalPuzzle onBack={() => setView("progress")} onSolved={() => markSolved(current.id)}/>}
    {view === "puzzle" && current.id === "timeline-reconstruction" && <TimelinePuzzle onBack={() => setView("progress")} onSolved={() => markSolved(current.id)}/>}
    {view === "success" && <div className="success fade"><div className="check">✓</div><p className="eyebrow">ÉNIGME RÉSOLUE</p><h2>Fragment {String(justSolved.fragmentId).padStart(2, "0")} récupéré.</h2><p>Un élément de votre mémoire a été restauré.</p><div className="reveal"><span>FRAGMENT {String(justSolved.fragmentId).padStart(2, "0")}</span><strong>{fragments.find((fragment) => fragment.id === justSolved.fragmentId)?.preview}</strong></div><Action onClick={() => setView("progress")}>Continuer</Action></div>}
    {view === "fragments" && <div className="content fade"><p className="eyebrow">ARCHIVE PERSONNELLE</p><Title title="Fragments" count={solved}/><p className="subcopy">Chaque fragment est conservé sans interprétation.</p><Grid unlocked={state.unlockedFragmentIds} onOpen={setOpen}/></div>}
    {view === "meta" && <div className="content meta fade"><button className="back" onClick={() => setView("progress")}>← Retour</button><p className="eyebrow">PHASE FINALE</p><b>◇</b><h2>Méta-énigme</h2><p>Les six fragments doivent maintenant être assemblés.</p><small>Cet espace accueillera bientôt la dernière étape de récupération.</small></div>}
    {!["home","puzzle","success","meta"].includes(view) && <nav><button className={view === "progress" ? "active" : ""} onClick={() => setView("progress")}>Progression</button><button className={view === "fragments" ? "active" : ""} onClick={() => setView("fragments")}>Fragments</button></nav>}
  </section>{open && <div className="modal-bg" onClick={() => setOpen(null)}><article onClick={(e) => e.stopPropagation()}><button onClick={() => setOpen(null)}>×</button><p className="eyebrow">FRAGMENT 01</p><strong>◇ 17 ↑ 04 ○</strong><p>Fragment de démonstration. Son sens n’est volontairement pas expliqué.</p></article></div>}{typeof window !== "undefined" && location.search.includes("dev") && <button className="reset" onClick={reset}>Réinitialiser</button>}</main>;
}
function Action({children,onClick}:{children:React.ReactNode;onClick:()=>void}) { return <button className="action" onClick={onClick}>{children}<span>→</span></button>; }
function Dots({count}:{count:number}) { return <div className="dots">{fragments.map((f) => <i className={f.id <= count ? "done" : ""} key={f.id}/>)}</div>; }
function Title({title,count}:{title:string;count:number}) { return <div className="title"><h2>{title}</h2><span>{String(count).padStart(2,"0")} / 06</span></div>; }
function Grid({unlocked,onOpen}:{unlocked:number[];onOpen?:(id:number)=>void}) { return <div className="grid">{fragments.map((f) => {const yes=unlocked.includes(f.id); return <button disabled={!yes} onClick={() => yes && onOpen?.(f.id)} className={yes ? "unlocked" : ""} key={f.id}><span>FRAGMENT {String(f.id).padStart(2,"0")}</span>{yes?<strong>{f.preview}</strong>:<b>⌁</b>}</button>;})}</div>; }
