"use client";
import { useEffect, useState } from "react";
import { fragments } from "@/games/fragments";
import { puzzles } from "@/games/puzzles";
import { emptyGameState, loadGameState, saveGameState, type GameState } from "@/lib/gameState";

type View = "home" | "progress" | "fragments" | "puzzle" | "success" | "meta";
const check = (answer: string) => answer.trim().toLocaleLowerCase("fr-FR") === "dossier 4x100";

export default function Home() {
  const [state, setState] = useState<GameState>(emptyGameState), [view, setView] = useState<View>("home"), [ready, setReady] = useState(false), [answer, setAnswer] = useState(""), [error, setError] = useState(false), [open, setOpen] = useState<number | null>(null);
  useEffect(() => { const timer = window.setTimeout(() => { const persisted = loadGameState(); setState(persisted); setView(persisted.started ? "progress" : "home"); setReady(true); }, 0); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (ready) saveGameState(state); }, [ready, state]);
  const solved = state.solvedPuzzleIds.length, complete = solved === puzzles.length, current = puzzles[0];
  const begin = () => { setState((s) => ({ ...s, started: true })); setView("progress"); };
  const validate = () => { if (!check(answer)) { setError(true); return; } setState((s) => ({ ...s, solvedPuzzleIds: s.solvedPuzzleIds.includes(current.id) ? s.solvedPuzzleIds : [...s.solvedPuzzleIds, current.id], unlockedFragmentIds: s.unlockedFragmentIds.includes(1) ? s.unlockedFragmentIds : [...s.unlockedFragmentIds, 1] })); setView("success"); };
  const reset = () => { localStorage.removeItem("dossier-4x100-game-state"); setState(emptyGameState); setView("home"); setAnswer(""); };
  return <main className="app-shell"><i className="orb one"/><i className="orb two"/><section className="app-frame">
    {view !== "home" && <header><button onClick={() => setView("progress")}>DOSSIER 4x100</button><span className="header-code">ARCHIVE / 04.100</span><i className="live"/></header>}
    {view === "home" && <div className="home fade"><div className="monogram">D</div><p className="eyebrow">SYSTÈME D’ARCHIVAGE · UNITÉ 04</p><h1>DOSSIER<br/>4x100</h1><p className="subtitle">Système de récupération mémorielle</p><p className="intro">Votre mémoire a été fragmentée.<br/>Six fragments doivent être récupérés.<br/>Résolvez les énigmes pour les retrouver.</p><Dots count={0}/><Action onClick={begin}>Initialiser la session</Action><small>Accès personnel · Protocole 04.100</small></div>}
    {view === "progress" && <div className="content fade"><p className="eyebrow">ÉTAT DE LA RÉCUPÉRATION</p><Title title="Fragments récupérés" count={solved}/><Dots count={solved}/><Grid unlocked={state.unlockedFragmentIds}/><section className="next"><p className="eyebrow">{complete ? "SYSTÈME COMPLET" : "PROCHAINE ÉTAPE"}</p>{complete ? <><h3>Tous les fragments ont été récupérés.</h3><p>Vous avez maintenant tout ce qu’il vous faut.</p><Action onClick={() => setView("meta")}>Assembler les fragments</Action></> : solved === 0 ? <><h3><em>01</em> Signal mémoriel</h3><p>Une première vérification d’intégrité vous attend.</p><Action onClick={() => setView("puzzle")}>Commencer l’énigme</Action></> : <><h3><em>02</em> Fragment absent</h3><p>Cette énigme sera ajoutée ultérieurement.</p><button className="action unavailable" disabled>En attente</button></>}</section></div>}
    {view === "puzzle" && <div className="content puzzle fade"><button className="back" onClick={() => setView("progress")}>← Retour</button><p className="eyebrow">ÉNIGME 01</p><h2>Signal mémoriel</h2><p className="intro">Un signal a été détecté dans les données de la session.</p><div className="puzzle-box"><b>◇</b><p>Pour cette démonstration, saisissez le nom du système affiché à l’accueil.</p></div><label htmlFor="answer">Votre réponse</label><input id="answer" autoCapitalize="none" value={answer} onChange={(e) => {setAnswer(e.target.value);setError(false);}} onKeyDown={(e) => e.key === "Enter" && validate()} placeholder="Saisir la réponse"/><p className="error">{error && "Réponse non reconnue. Observez les informations déjà à votre disposition."}</p><Action onClick={validate}>Valider</Action></div>}
    {view === "success" && <div className="success fade"><div className="check">✓</div><p className="eyebrow">ÉNIGME RÉSOLUE</p><h2>Fragment 01 récupéré.</h2><p>Un élément de votre mémoire a été restauré.</p><div className="reveal"><span>FRAGMENT 01</span><strong>◇ 17 ↑ 04 ○</strong></div><Action onClick={() => setView("progress")}>Continuer</Action></div>}
    {view === "fragments" && <div className="content fade"><p className="eyebrow">ARCHIVE PERSONNELLE</p><Title title="Fragments" count={solved}/><p className="subcopy">Chaque fragment est conservé sans interprétation.</p><Grid unlocked={state.unlockedFragmentIds} onOpen={setOpen}/></div>}
    {view === "meta" && <div className="content meta fade"><button className="back" onClick={() => setView("progress")}>← Retour</button><p className="eyebrow">PHASE FINALE</p><b>◇</b><h2>Méta-énigme</h2><p>Les six fragments doivent maintenant être assemblés.</p><small>Cet espace accueillera bientôt la dernière étape de récupération.</small></div>}
    {!["home","puzzle","success","meta"].includes(view) && <nav><button className={view === "progress" ? "active" : ""} onClick={() => setView("progress")}>Progression</button><button className={view === "fragments" ? "active" : ""} onClick={() => setView("fragments")}>Fragments</button></nav>}
  </section>{open && <div className="modal-bg" onClick={() => setOpen(null)}><article onClick={(e) => e.stopPropagation()}><button onClick={() => setOpen(null)}>×</button><p className="eyebrow">FRAGMENT 01</p><strong>◇ 17 ↑ 04 ○</strong><p>Fragment de démonstration. Son sens n’est volontairement pas expliqué.</p></article></div>}{typeof window !== "undefined" && location.search.includes("dev") && <button className="reset" onClick={reset}>Réinitialiser</button>}</main>;
}
function Action({children,onClick}:{children:React.ReactNode;onClick:()=>void}) { return <button className="action" onClick={onClick}>{children}<span>→</span></button>; }
function Dots({count}:{count:number}) { return <div className="dots">{fragments.map((f) => <i className={f.id <= count ? "done" : ""} key={f.id}/>)}</div>; }
function Title({title,count}:{title:string;count:number}) { return <div className="title"><h2>{title}</h2><span>{String(count).padStart(2,"0")} / 06</span></div>; }
function Grid({unlocked,onOpen}:{unlocked:number[];onOpen?:(id:number)=>void}) { return <div className="grid">{fragments.map((f) => {const yes=unlocked.includes(f.id); return <button disabled={!yes} onClick={() => yes && onOpen?.(f.id)} className={yes ? "unlocked" : ""} key={f.id}><span>FRAGMENT {String(f.id).padStart(2,"0")}</span>{yes?<strong>{f.preview}</strong>:<b>⌁</b>}</button>;})}</div>; }
