"use client";

import { useState } from "react";
import { assetPath } from "@/lib/assetPath";

export function AudioPuzzle({ onBack, onSolved }: { onBack: () => void; onSolved: () => void }) {
  const [answer, setAnswer] = useState(""), [error, setError] = useState(false), [hintVisible, setHintVisible] = useState(false), [audioUnavailable, setAudioUnavailable] = useState(false);
  const validate = () => { if (answer.trim().toLocaleUpperCase("fr-FR") === "DIEPPE") onSolved(); else setError(true); };
  return <div className="content audio-puzzle fade"><button className="back" onClick={onBack}>← Retour</button><p className="eyebrow">ÉNIGME 03</p><h2>Minutes Crimes</h2><p className="audio-intro">Une affaire ancienne a été extraite des archives. Écoutez attentivement.</p><section className="audio-player"><div className="audio-player-head"><span>MINUTES CRIMES AVEC CAMILLE</span><i>ARCHIVE AUDIO / 01</i></div><div className="audio-art"><span>MC</span><b>LE MASQUE<br/>DE FER</b></div><audio controls preload="metadata" onError={() => setAudioUnavailable(true)}><source src={assetPath("/audio/minutes-crimes.m4a")} type="audio/mp4" />Votre navigateur ne prend pas en charge la lecture audio.</audio>{audioUnavailable && <p className="audio-error">Archive audio indisponible. Vérifiez que le fichier est présent dans <code>public/audio</code>.</p>}</section>{hintVisible ? <p className="hint"><b>Indice</b>Certaines choses se cachent là où une histoire commence.</p> : <button className="hint-button" onClick={() => setHintVisible(true)}>Afficher l’indice <span>+</span></button>}<div className="audio-validation"><label htmlFor="audio-answer">Quelle est votre réponse ?</label><input id="audio-answer" autoCapitalize="characters" autoComplete="off" value={answer} onChange={(event) => { setAnswer(event.target.value); setError(false); }} onKeyDown={(event) => event.key === "Enter" && validate()} placeholder="Saisir la réponse"/><p className="error">{error && "Ce n’est pas la bonne réponse."}</p><button className="action" onClick={validate}>Valider <span>→</span></button></div></div>;
}
