"use client";

import { useState } from "react";
import Image from "next/image";

export function MapPuzzle({ onBack, onSolved }: { onBack: () => void; onSolved: () => void }) {
  const [answer, setAnswer] = useState(""), [error, setError] = useState(false), [hintVisible, setHintVisible] = useState(false), [imageUnavailable, setImageUnavailable] = useState(false), [expanded, setExpanded] = useState(false);
  const validate = () => { if (answer.trim().toLocaleUpperCase("fr-FR") === "SKYNET") onSolved(); else setError(true); };
  return <div className="content map-puzzle fade"><button className="back" onClick={onBack}>← Retour</button><p className="eyebrow">ÉNIGME 04</p><h2>Hors écran</h2><p className="map-intro">La prochaine information ne se trouve pas dans cet écran.<br/><br/>6 fragments ont été dissimulés dans votre environnement.<br/><br/>Leur position n’est pas exacte.<br/>Mais leur territoire, lui, est indiqué.</p><button className="map-display" onClick={() => setExpanded(true)} aria-label="Agrandir la carte"><Image src="/images/enigme-04-map.png" alt="Carte des zones de recherche" width={1400} height={1800} unoptimized onError={() => setImageUnavailable(true)}/>{imageUnavailable && <span className="map-unavailable">Carte indisponible : ajoutez <code>public/images/enigme-04-map.png</code></span>}</button><p className="map-caption">La localisation est approximative. Cherche dans la zone indiquée.</p>{hintVisible ? <p className="hint"><b>Indice</b>Six fragments. Six lettres. Un seul mot.</p> : <button className="hint-button" onClick={() => setHintVisible(true)}>Afficher l’indice <span>+</span></button>}<div className="map-validation"><label htmlFor="map-answer">Mot trouvé…</label><input id="map-answer" autoCapitalize="characters" autoComplete="off" value={answer} onChange={(event) => { setAnswer(event.target.value); setError(false); }} onKeyDown={(event) => event.key === "Enter" && validate()} placeholder="Mot trouvé…"/><p className="error">{error && "Ce n’est pas le bon mot."}</p><button className="action" onClick={validate}>Valider <span>→</span></button></div>{expanded && <div className="map-overlay" onClick={() => setExpanded(false)}><button onClick={() => setExpanded(false)} aria-label="Fermer la carte">×</button><Image src="/images/enigme-04-map.png" alt="Carte des zones de recherche agrandie" width={1400} height={1800} unoptimized onError={() => setImageUnavailable(true)}/></div>}</div>;
}
